### ISSUE TITLE
apt issue with the way you have the scripts implemented

### ISSUE THREAD

**Issue by captainkyds** [bostrot/wsl-scripts#5]
to recreate install postfix via one of these scripts.. It requires user interaction which is not possible with however they are 
implementated. I imagine an apt update that also requires user input will also bug out and lock up.

**Comment by bostrot** [comment]
I guess this might help:

`export DEBIAN_FRONTEND=noninteractive`

Using the dart process controller is a bit tricky. I will have some more time soon then I will look into this.
