### ISSUE TITLE
WSL-Scripts Contributions

### ISSUE THREAD

**Issue by Ragdata** [bostrot/wsl-scripts#6]
Hey Eric,

I love your WSL2 Manager package and only just noticed the Community Action Scripts feature - which I thought was an awesome idea.

So, I did a quick little script to submit as a tester with a few more substantial ones to follow, but it doesn't appear that the repo is set up for contributions?

I followed the usual practice:

1. Fork the repo
2. Create a feature branch (ragdata/full-upgrade)
3. Tried to push to the repo but couldn't ...

I was intending to open a pull request because I figured that would be the process, but I obviously got that wrong.  Could you advise the correct process to submit updates ... or whether you're interested in receiving them at all I guess?

Thanks,

Rags

**Comment by bostrot** [comment]
Hi, thanks for the kind words :)

First of all, I am very interested in receiving PRs here! There was a PR before, so it should just work. 

Normally the process would be something like this; maybe you forgot something?

1. Fork the repo
2. Push your changed code to your repo
3. In your repo, click on "Contribute"
4. Then, on Open Pull Request, as in the screenshot below

![image](https://user-images.githubusercontent.com/7342321/233070741-7eaa2330-8e4f-47fb-83d4-f54bd246d6e4.png)

[Here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) is additional information that might help you.

Does this help you?

**Comment by Ragdata** [comment]
It does indeed ... to be truthful, yours will be the first that I've attempted to push changes to.

So, I ALMOST got it right, but these instructions will help me get all the way there.

Yes, I feel like an idiot - but you'll have my first submission within the next 24 hours, and more to follow from there.

Thank you.
